version: '3'
services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - 3100:3100
  react:
    build:
      dockerfile: Dockerfile.dev
      context: ./shell-to-driver-01-starting-code
    ports:
      - 3000:3000
